[build]
  command = "npm run build"
  publish = "dist"

# Redirect old domain to new domain
[[redirects]]
  from = "https://notes.sujayvaidya.co.in/*"
  to = "https://notes.nukerc.com/:splat"
  status = 301
  force = true

# React SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200